name: samantha
favicon: null
layout_spectrum: 0.5830666350666434
typography_spectrum: 0.6680369942914695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.7374386272858828
  lightness: 0.9882298458833247
  saturation: 0.8133472469635308
  rhythmicContrast: 0.7782535497099161
purpose: []
